dist: trusty
sudo: required
services: [docker]
language: generic

jobs:
  include:
    - if: type IN (api, cron)

      install:
        - docker build -t mirror .

      before_script:
        - git config user.name "Heroku Databot"
        - git config user.email "hawkrives+sto-catalog-databot@gmail.com"

      script:
        - docker run -it -v $(pwd):/app mirror /app/mirror.sh || (echo "A problem occurred" && exit 0)

      after_script:
        - git add .
        - git commit -m "catalog update $(date)" || (echo "No updates found." && exit 0)
        - git push "https://$GITHUB_OAUTH@github.com/StoDevX/stolaf-catalog.git" master
